name: Test pipeline github actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display classic message
        run: echo "This is a classic message"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display build message
        run: echo "This is a build message"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display deploy message
        run: echo "This is a deploy message"